### ISSUE TITLE
then is not a function

### ISSUE THREAD

**Issue by vaske** [bjoerge/debounce-promise#28]
Hi @bjoerge,

I have one issue with debounce function, here is what I'm doing

```
const fakeResponseFunc = ({ status, data}) => {
  return new Promise((resolve, reject) => resolve({ status, data })
};

function expensiveOperation() {
  return Promise.resolve(fakeResponseFunc({
      status: 200,
      data: "something",
    }))
    }

const afterDebounce = debounce(expensiveOperation, 300);

afterDebounce.then(({ data }) => console.log(data))

```
I'm getting for afterDebounce.then is not a function, I use latest v3.1.2 version this is really basic sample and weird that it doesn't do debounce as desired.

**Comment by bjoerge** [comment]
`debounce` returns a function, try `afterDebounce().then(({ data }) => console.log(data))`
